<?php

// =============================================================================
// FUNCTIONS/INCLUDES/LANGUAGE-LIST.PHP
// -----------------------------------------------------------------------------
// List of types of contact, used on Schema.org:ContactPoint:availableLanguage
// =============================================================================

// =============================================================================
// TABLE OF CONTENTS
// -----------------------------------------------------------------------------
//   01. Array of values
// =============================================================================

// Array of values
// =============================================================================

return array(
  "Akan",
  "Amharic",
  "Arabic",
  "Assamese",
  "Awadhi",
  "Azerbaijani",
  "Balochi",
  "Belarusian",
  "Bengali",
  "Bhojpuri",
  "Burmese",
  "Cantonese",
  "Cebuano",
  "Chewa",
  "Chhattisgarhi",
  "Chittagonian",
  "Czech",
  "Deccan",
  "Dhundhari",
  "Dutch",
  "English",
  "French",
  "Fula",
  "Gan",
  "German",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Hakka",
  "Haryanvi",
  "Hausa",
  "Hiligaynon",
  "Hindi / Urdu",
  "Hmong",
  "Hungarian",
  "Igbo",
  "Ilokano",
  "Italian",
  "Japanese",
  "Javanese",
  "Jin",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Kinyarwanda",
  "Kirundi",
  "Konkani",
  "Korean",
  "Kurdish",
  "Madurese",
  "Magahi",
  "Maithili",
  "Malagasy",
  "Malay/Indonesian",
  "Malayalam",
  "Mandarin",
  "Marathi",
  "Marwari",
  "Min Bei",
  "Min Dong",
  "Min Nan",
  "Mossi",
  "Nepali",
  "Oriya",
  "Oromo",
  "Pashto",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Quechua",
  "Romanian",
  "Russian",
  "Saraiki",
  "Serbo-Croatian",
  "Shona",
  "Sindhi",
  "Sinhalese",
  "Somali",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swedish",
  "Sylheti",
  "Tagalog",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Uyghur",
  "Uzbek",
  "Vietnamese",
  "Wu",
  "Xhosa",
  "Xiang",
  "Yoruba",
  "Zulu",
);
